<a href="https://colab.research.google.com/github/dimaswisodewo/Regression-using-ANN/blob/main/artificial_neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

## Importing the libraries

In [64]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [65]:
tf.__version__

'2.4.0'

## Part 1 - Data Preprocessing

## Importing the Dataset

In [66]:
!ls "/content/drive/MyDrive/Colab Notebooks/Deep Learning/Regression/Artificial Neural Network (ANN)/"

artificial_neural_network.ipynb  Folds5x2_pp.xlsx


In [67]:
dataset = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Deep Learning/Regression/Artificial Neural Network (ANN)/Folds5x2_pp.xlsx')

In [68]:
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

Features consist of hourly average ambient variables
- Temperature (T) in the range 1.81°C and 37.11°C,
- Ambient Pressure (AP) in the range 992.89-1033.30 milibar,
- Relative Humidity (RH) in the range 25.56% to 100.16%
- Exhaust Vacuum (V) in teh range 25.36-81.56 cm Hg
- Net hourly electrical energy output (EP) 420.26-495.76 MW
The averages are taken from various sensors located around the plant that record the ambient variables every second. The variables are given without normalization.

In [69]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [70]:
X

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [71]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

## Splitting the dataset into the Training set and Test set

In [72]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

print('Train set: ', len(X_train))
print('Test set: ', len(X_test))

Train set:  7654
Test set:  1914


## Feature Scaling

In [73]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [74]:
X_train

array([[-1.14, -0.89,  0.67,  0.52],
       [-0.81, -0.01,  0.45,  0.15],
       [ 1.77,  1.85,  0.24, -1.88],
       ...,
       [-0.38, -1.25,  0.85,  0.13],
       [-0.92, -1.04,  1.55,  0.88],
       [ 1.7 ,  1.06, -1.2 , -2.42]])

In [75]:
X_test

array([[ 1.21,  1.85, -0.62, -0.29],
       [-0.29, -0.4 ,  1.39,  0.77],
       [-0.65, -0.89,  1.01,  1.77],
       ...,
       [-1.  , -0.75,  1.77,  1.02],
       [ 1.02, -0.51, -1.65, -0.96],
       [-0.32, -1.13, -1.03,  0.07]])

# Part 2 - Building the ANN

In [76]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))

# Part 3 - Training the ANN

## Compiling the ANN

In [77]:
ann.compile(optimizer='adam', loss='mse', metrics=['mse', 'mae', 'mape'])

## Training the ANN model on the Training set

In [78]:
ann.fit(X_train_scaled, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 206075.8206 - mse: 206075.8206 - mae: 453.6512 - mape: 99.8329
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 199838.9901 - mse: 199838.9901 - mae: 446.7554 - mape: 98.3527
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 176591.4315 - mse: 176591.4315 - mae: 419.6197 - mape: 92.3576
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 129911.7404 - mse: 129911.7404 - mae: 357.4015 - mape: 78.5732
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 73290.6229 - mse: 73290.6229 - mae: 258.9697 - mape: 56.8528
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 34879.7627 - mse: 34879.7627 - mae: 166.4033 - mape: 36.5624
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 19485.7447 - mse: 19485.7447 - mae: 117.2573 - mape: 25.9397
Epoch 8/100
240/240 [===================

## Predicting the results of the Test set

In [79]:
y_pred = ann.predict(X_test)

In [80]:
np.set_printoptions(precision=2)
output = np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1)

In [81]:
output
# first column: predicted value
# second column: observed value

array([[430.58, 431.23],
       [459.07, 460.01],
       [463.03, 461.14],
       ...,
       [470.08, 473.26],
       [441.9 , 438.  ],
       [462.08, 463.28]])

In [93]:
for x in range(len(y_test)):
  print('predicted: ', y_pred[x,0],' - observed: ', y_test[x])

predicted:  430.57816  - observed:  431.23
predicted:  459.06747  - observed:  460.01
predicted:  463.03012  - observed:  461.14
predicted:  449.51395  - observed:  445.9
predicted:  458.81732  - observed:  451.29
predicted:  429.96957  - observed:  432.68
predicted:  473.6444  - observed:  477.5
predicted:  457.6762  - observed:  459.68
predicted:  474.6486  - observed:  477.5
predicted:  447.4809  - observed:  444.99
predicted:  442.0602  - observed:  444.37
predicted:  442.0233  - observed:  437.04
predicted:  445.646  - observed:  442.34
predicted:  440.1009  - observed:  440.74
predicted:  437.18402  - observed:  436.55
predicted:  454.95938  - observed:  460.24
predicted:  445.77603  - observed:  448.66
predicted:  438.4067  - observed:  432.94
predicted:  450.82333  - observed:  452.82
predicted:  427.62372  - observed:  432.2
predicted:  425.21942  - observed:  430.96
predicted:  431.68005  - observed:  434.65
predicted:  474.76965  - observed:  473.56
predicted:  438.53125  - 